### ISSUE TITLE
[咨询为啥vite不行]：您好，想咨询一下有没有遇到vite引入后的这个问题，谢谢

### ISSUE THREAD

**Issue by nyhxiaoning** [guijixing/vue-code-link#1]
报错信息如下，想问问你那边有没有出现这样的问题
使用环境：nodev16.5.0环境安装
~~~

path.js:25 
        
       Uncaught ReferenceError: process is not defined
    at node_modules/path/path.js (path.js:25:17)
    at __require (chunk-QOVRSCHT.js?v=1ab1db7b:11:50)
    at node_modules/@guijixing/vue-code-link/add-location-loader/config.js (config.js:2:14)
    at __require (chunk-QOVRSCHT.js?v=1ab1db7b:11:50)
    at node_modules/@guijixing/vue-code-link/index.js (index.js:4:31)
    at __require (chunk-QOVRSCHT.js?v=1ab1db7b:11:50)
    at dep:@guijixing_vue-code-link:1:16


~~~

**Comment by nyhxiaoning** [comment]
为了避免是我其他插件的影响，我再次重建一个vue3-vite非ts项目测试，没有报错了，但是不知道怎样触发
，咨询一下：shift+鼠标左键，一直不可以

**Comment by guijixing** [comment]
配置的是shift+鼠标右键,修改github上没推上来

**Comment by nyhxiaoning** [comment]
![image](https://user-images.githubusercontent.com/34833782/177244442-2d7b9ca9-19cd-4cf8-9cc8-46b1ecfabc1f.png)
shift+鼠标右键，直接再当前项目下，生成一个null文件，我想问题，是不是还得配置一下，相对文件路径或是相对地址引用之类

**Comment by nyhxiaoning** [comment]
我用webpack框架，配置可以定位，就是vite框架不可以，不知道哪一步出问题了

**Comment by nyhxiaoning** [comment]
我想问问，您这个插件的node版本和vite版本是多少？

**Comment by guijixing** [comment]
"vite": "2.5.7","node": "v14.16.0",

**Comment by guijixing** [comment]
![image](https://user-images.githubusercontent.com/22042837/177246032-f4088ca6-9c26-499d-84d3-1c25df10b8d3.png)
看你dom生成的地址是多少

**Comment by guijixing** [comment]
看你dom上的地址是多少
![image](https://user-images.githubusercontent.com/22042837/177246221-03ea46f1-8e05-435b-8627-cbf17689b1ab.png)

**Comment by guijixing** [comment]
![123](https://user-images.githubusercontent.com/22042837/177247094-17215a38-ddfa-4e7e-9758-47b2a052b263.gif)

**Comment by nyhxiaoning** [comment]
我的参考没有参考好，我这边的问题，
插件放在vue（）前面就好了，真的是打扰你了，谢谢
